base_dir: '/content/drive/MyDrive/Colab Notebooks/NFFA-SEM/data/processed'
batch_size: 32
num_epochs: 10
learning_rate: 0.001
input_size: [224, 224]
random_seed: 42
subset_ratio: 0.1
save_model_path: '/content/drive/MyDrive/Colab Notebooks/NFFA-SEM/models/model.pth'
logs_dir: '/content/drive/MyDrive/Colab Notebooks/NFFA-SEM/logs/'
output_base_dir: '/content/drive/MyDrive/Colab Notebooks/NFFA-SEM/outputs/'